name: Build Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Yarn
      run: npm install yarn --legacy-peer-deps

    - name: Install dependencies
      run: yarn install

    - name: Build the project
      run: npx gatsby build
